CREATE DATABASE HOSPITAL;

DROP TABLE IF EXISTS Hospital_Data;

CREATE TABLE HOSPITAL_DATA (
	HOSPITAL_NAME VARCHAR(100),
	LOCATION VARCHAR(50),
	DEPARTMENT VARCHAR(50),
	DOCTORS_COUNT TEXT,
	PATIENTS_COUNT TEXT,
	ADMISSION_DATE TEXT,
	DISCHARGE_DATE TEXT,
	MEDICAL_EXPENSES NUMERIC(12, 2)
);


COPY HOSPITAL_DATA (
	HOSPITAL_NAME,
	LOCATION,
	DEPARTMENT,
	DOCTORS_COUNT,
	PATIENTS_COUNT,
	ADMISSION_DATE,
	DISCHARGE_DATE,
	MEDICAL_EXPENSES
)
FROM
	'D:\DATA ANALYST LEARNING\hospital_data .csv' DELIMITER ',' CSV HEADER;


SELECT * FROM hospital_data;

SELECT DISTINCT doctors_count
FROM hospital_data
WHERE doctors_count !~ '^[0-9]+$';

UPDATE hospital_data
SET doctors_count = NULL
WHERE doctors_count !~ '^[0-9]+$';

ALTER TABLE hospital_data
ALTER COLUMN doctors_count TYPE INT
USING doctors_count::INT;

ALTER TABLE hospital_data
ALTER COLUMN patients_count TYPE INT
USING patients_count::INT;

ALTER TABLE hospital_data
ALTER COLUMN admission_date TYPE DATE
USING admission_date::DATE;

ALTER TABLE hospital_data
ALTER COLUMN discharge_date TYPE DATE
USING discharge_date::DATE;

SELECT * FROM hospital_data;



--Assignment question

--Q1. Total Number of Patients.

SELECT
	SUM(PATIENTS_COUNT) AS TOTAL_PATIENTS
FROM
	HOSPITAL_DATA;

--Q2. Average Number of Doctors per Hospital

SELECT
	AVG(DOCTORS_COUNT) AS AVG_DOCTORS_PER_HOSPITAL
FROM
	HOSPITAL_DATA;


--Q3. Top 3 Departments with the Highest Number of Patients

SELECT
	DEPARTMENT,
	COUNT(*) AS PATIENTS_COUNT
FROM
	HOSPITAL_DATA
GROUP BY
	DEPARTMENT
ORDER BY
	PATIENTS_COUNT DESC
LIMIT
	3;


--Q4. Hospital with the Maximum Medical Expenses 

SELECT
	HOSPITAL_NAME,
	SUM(MEDICAL_EXPENSES) AS TOTAL_EXPENSES
FROM
	HOSPITAL_DATA
GROUP BY
	HOSPITAL_NAME
ORDER BY
	TOTAL_EXPENSES DESC
LIMIT
	1;


--Q5. Daily Average Medical Expenses

SELECT
	ADMISSION_DATE,
	AVG(MEDICAL_EXPENSES) AS AVG_DAILY_EXPENSES
FROM
	HOSPITAL_DATA
GROUP BY
	ADMISSION_DATE
ORDER BY
	ADMISSION_DATE;


--Q6. Longest Hospital Stay


SELECT
	HOSPITAL_NAME,
	DEPARTMENT,
	LOCATION,
	(DISCHARGE_DATE - ADMISSION_DATE) AS STAY_DAYS
FROM
	HOSPITAL_DATA
ORDER BY
	STAY_DAYS DESC
LIMIT
	1;
--Q7. Total Patients Treated Per City

SELECT
	LOCATION,
	SUM(PATIENTS_COUNT) AS TOTAL_PATIENTS
FROM
	HOSPITAL_DATA
GROUP BY
	LOCATION
ORDER BY
	TOTAL_PATIENTS DESC;


--Q8. Average Length of Stay Per Department

SELECT
	DEPARTMENT,
	AVG(DISCHARGE_DATE - ADMISSION_DATE) AS AVG_STAY_DAYS
FROM
	HOSPITAL_DATA
GROUP BY
	DEPARTMENT
ORDER BY
	AVG_STAY_DAYS DESC;


--Q9. Identify the Department with the Lowest Number of Patients

SELECT
	DEPARTMENT,
	SUM(PATIENTS_COUNT) AS TOTAL_PATIENTS
FROM
	HOSPITAL_DATA
GROUP BY
	DEPARTMENT
ORDER BY
	TOTAL_PATIENTS ASC
LIMIT
	1;


--Q10.  Monthly Medical Expenses Report 

SELECT
	DATE_TRUNC('month', ADMISSION_DATE) AS MONTH,
	SUM(MEDICAL_EXPENSES) AS TOTAL_EXPENSES
FROM
	HOSPITAL_DATA
GROUP BY
	MONTH
ORDER BY
	MONTH;





